<?php

namespace Database\Seeders;

use App\Models\Currency; // Adjust App\Models\ path if your model is elsewhere
use Illuminate\Database\Seeder;

// use Illuminate\Support\Facades\DB; // Uncomment if you prefer DB facade for large inserts

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencyData = [
            [
                'code' => 'CHF',
                'name' => 'Swiss Franc',
                'symbol' => 'Fr',
                'symbol_position' => 'prefix',
                'exchange_rate' => '0.8309490000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'CLP',
                'name' => 'Chilean Peso',
                'symbol' => '$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '941.3800000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'CNY',
                'name' => 'Chinese Yuan',
                'symbol' => '¥',
                'symbol_position' => 'prefix',
                'exchange_rate' => '7.2253500000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'GHS',
                'name' => 'Ghanaian Cedi',
                'symbol' => '₵',
                'symbol_position' => 'prefix',
                'exchange_rate' => '15.3100000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'USD',
                'name' => 'US Dollar',
                'symbol' => '$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '1.0000000000',
                'is_base_currency' => 1,
                'is_active' => 1,
            ],
            [
                'code' => 'NZD',
                'name' => 'New Zealand Dollar',
                'symbol' => 'NZ$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '1.6954370000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'PEN',
                'name' => 'Peruvian Sol',
                'symbol' => 'S/',
                'symbol_position' => 'prefix',
                'exchange_rate' => '3.6776380000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'SEK',
                'name' => 'Swedish Krona',
                'symbol' => 'kr',
                'symbol_position' => 'suffix',
                'exchange_rate' => '9.7183580000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'HKD',
                'name' => 'Hong Kong Dollar',
                'symbol' => 'HK$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '7.7748650000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'PGK',
                'name' => 'Papua New Guinean Kina',
                'symbol' => 'K',
                'symbol_position' => 'prefix',
                'exchange_rate' => '4.0582500000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'HRK',
                'name' => 'Croatian Kuna',
                'symbol' => 'kn',
                'symbol_position' => 'suffix',
                'exchange_rate' => '6.7107160000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'HUF',
                'name' => 'Hungarian Forint',
                'symbol' => 'Ft',
                'symbol_position' => 'suffix',
                'exchange_rate' => '361.7551830000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'AED',
                'name' => 'United Arab Emirates Dirham',
                'symbol' => 'د.إ',
                'symbol_position' => 'prefix',
                'exchange_rate' => '3.6729900000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'PHP',
                'name' => 'Philippine Peso',
                'symbol' => '₱',
                'symbol_position' => 'prefix',
                'exchange_rate' => '55.5644970000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'ETH',
                'name' => 'Ethereum',
                'symbol' => 'Ξ',
                'symbol_position' => 'prefix',
                'exchange_rate' => '0.0002600000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'IDR',
                'name' => 'Indonesian Rupiah',
                'symbol' => 'Rp',
                'symbol_position' => 'prefix',
                'exchange_rate' => '16531.4799660000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'ILS',
                'name' => 'Israeli New Shekel',
                'symbol' => '₪',
                'symbol_position' => 'prefix',
                'exchange_rate' => '3.5773600000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'JPY',
                'name' => 'Japanese Yen',
                'symbol' => '¥',
                'symbol_position' => 'prefix',
                'exchange_rate' => '145.4297500000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'KES',
                'name' => 'Kenyan Shilling',
                'symbol' => 'KSh',
                'symbol_position' => 'prefix',
                'exchange_rate' => '129.3500000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'KRW',
                'name' => 'South Korean Won',
                'symbol' => '₩',
                'symbol_position' => 'prefix',
                'exchange_rate' => '1399.3623610000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'KWD',
                'name' => 'Kuwaiti Dinar',
                'symbol' => 'د.ك',
                'symbol_position' => 'prefix',
                'exchange_rate' => '0.3067980000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'LKR',
                'name' => 'Sri Lankan Rupee',
                'symbol' => '₨',
                'symbol_position' => 'prefix',
                'exchange_rate' => '300.3346440000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'MAD',
                'name' => 'Moroccan Dirham',
                'symbol' => 'د.م.',
                'symbol_position' => 'prefix',
                'exchange_rate' => '9.2622500000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'MXN',
                'name' => 'Mexican Peso',
                'symbol' => '$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '19.5189500000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'MYR',
                'name' => 'Malaysian Ringgit',
                'symbol' => 'RM',
                'symbol_position' => 'prefix',
                'exchange_rate' => '4.3140000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'NGN',
                'name' => 'Nigerian Naira',
                'symbol' => '₦',
                'symbol_position' => 'prefix',
                'exchange_rate' => '1608.5700000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'NOK',
                'name' => 'Norwegian Krone',
                'symbol' => 'kr',
                'symbol_position' => 'suffix',
                'exchange_rate' => '10.4356050000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'PKR',
                'name' => 'Pakistani Rupee',
                'symbol' => '₨',
                'symbol_position' => 'prefix',
                'exchange_rate' => '281.8992760000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'PLN',
                'name' => 'Polish Złoty',
                'symbol' => 'zł',
                'symbol_position' => 'suffix',
                'exchange_rate' => '3.7826300000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'QAR',
                'name' => 'Qatari Riyal',
                'symbol' => '﷼',
                'symbol_position' => 'prefix',
                'exchange_rate' => '3.6410000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'RON',
                'name' => 'Romanian Leu',
                'symbol' => 'lei',
                'symbol_position' => 'suffix',
                'exchange_rate' => '4.5547000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'SAR',
                'name' => 'Saudi Riyal',
                'symbol' => '﷼',
                'symbol_position' => 'prefix',
                'exchange_rate' => '3.7509850000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'SBD',
                'name' => 'Solomon Islands Dollar',
                'symbol' => 'SI$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '8.3300370000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'SGD',
                'name' => 'Singapore Dollar',
                'symbol' => 'S$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '1.2989150000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'THB',
                'name' => 'Thai Baht',
                'symbol' => '฿',
                'symbol_position' => 'prefix',
                'exchange_rate' => '33.0703330000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'TOP',
                'name' => 'Tongan Paʻanga',
                'symbol' => 'T$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '2.4077600000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'TRY',
                'name' => 'Turkish Lira',
                'symbol' => '₺',
                'symbol_position' => 'prefix',
                'exchange_rate' => '38.7350990000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'TWD',
                'name' => 'New Taiwan Dollar',
                'symbol' => 'NT$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '30.1250000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'TZS',
                'name' => 'Tanzanian Shilling',
                'symbol' => 'TSh',
                'symbol_position' => 'prefix',
                'exchange_rate' => '2684.9990000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'UGX',
                'name' => 'Ugandan Shilling',
                'symbol' => 'USh',
                'symbol_position' => 'prefix',
                'exchange_rate' => '3668.6191050000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'UYU',
                'name' => 'Uruguayan Peso',
                'symbol' => '$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '41.7772250000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'VND',
                'name' => 'Vietnamese Đồng',
                'symbol' => '₫',
                'symbol_position' => 'suffix',
                'exchange_rate' => '25960.0000000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'VUV',
                'name' => 'Vanuatu Vatu',
                'symbol' => 'VT',
                'symbol_position' => 'suffix',
                'exchange_rate' => '118.7220000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'XAF',
                'name' => 'CFA Franc BEAC',
                'symbol' => 'FCFA',
                'symbol_position' => 'suffix',
                'exchange_rate' => '583.8234360000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'XOF',
                'name' => 'CFA Franc BCEAO',
                'symbol' => 'CFA',
                'symbol_position' => 'suffix',
                'exchange_rate' => '583.8234360000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'ZAR',
                'name' => 'South African Rand',
                'symbol' => 'R',
                'symbol_position' => 'prefix',
                'exchange_rate' => '18.2507720000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'ARS',
                'name' => 'Argentine Peso',
                'symbol' => '$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '1112.5150000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'AUD',
                'name' => 'Australian Dollar',
                'symbol' => 'A$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '1.5611710000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'BDT',
                'name' => 'Bangladeshi Taka',
                'symbol' => '৳',
                'symbol_position' => 'prefix',
                'exchange_rate' => '121.9014240000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'BGN',
                'name' => 'Bulgarian Lev',
                'symbol' => 'лв',
                'symbol_position' => 'suffix',
                'exchange_rate' => '1.7420000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'BHD',
                'name' => 'Bahraini Dinar',
                'symbol' => '.د.ب',
                'symbol_position' => 'prefix',
                'exchange_rate' => '0.3769550000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'BRL',
                'name' => 'Brazilian Real',
                'symbol' => 'R$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '5.6638000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'BTC',
                'name' => 'Bitcoin',
                'symbol' => '₿',
                'symbol_position' => 'prefix',
                'exchange_rate' => 0.0000097176,
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'CAD',
                'name' => 'Canadian Dollar',
                'symbol' => 'CA$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '1.3915060000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'COP',
                'name' => 'Colombian Peso',
                'symbol' => '$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '4305.8886540000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'CZK',
                'name' => 'Czech Koruna',
                'symbol' => 'Kč',
                'symbol_position' => 'suffix',
                'exchange_rate' => '22.1815540000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'DKK',
                'name' => 'Danish Krone',
                'symbol' => 'kr',
                'symbol_position' => 'suffix',
                'exchange_rate' => '6.6407150000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'EGP',
                'name' => 'Egyptian Pound',
                'symbol' => 'E£',
                'symbol_position' => 'prefix',
                'exchange_rate' => '50.6129720000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'EUR',
                'name' => 'Euro',
                'symbol' => '€',
                'symbol_position' => 'suffix',
                'exchange_rate' => '0.8900330000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'FJD',
                'name' => 'Fijian Dollar',
                'symbol' => 'FJ$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '2.2707000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'GBP',
                'name' => 'British Pound Sterling',
                'symbol' => '£',
                'symbol_position' => 'prefix',
                'exchange_rate' => '0.7552330000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'INR',
                'name' => 'Indian Rupee',
                'symbol' => '₹',
                'symbol_position' => 'prefix',
                'exchange_rate' => '85.5221800000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'ISK',
                'name' => 'Icelandic Króna',
                'symbol' => 'kr',
                'symbol_position' => 'suffix',
                'exchange_rate' => '130.5700000000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'JMD',
                'name' => 'Jamaican Dollar',
                'symbol' => 'J$',
                'symbol_position' => 'prefix',
                'exchange_rate' => '158.8287660000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
            [
                'code' => 'JOD',
                'name' => 'Jordanian Dinar',
                'symbol' => 'د.ا',
                'symbol_position' => 'prefix',
                'exchange_rate' => '0.7091490000',
                'is_base_currency' => 0,
                'is_active' => 1,
            ],
        ];

        foreach ($currencyData as $data) {
            Currency::firstOrCreate(['code' => $data['code']], $data);
        }
    }
}
