<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class OrderResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'public_id' => $this->public_id,
            'order_kind' => $this->order_kind,
            'purchasable_type' => $this->purchasable_type,
            'purchasable_id' => $this->purchasable_id,
            'variant_id' => $this->variant_id,
            'variant_snapshot' => $this->variant_snapshot,
            'bundle_item_selection' => $this->bundle_item_selection,
            'offering_group_selection' => $this->offering_group_selection,
            'quantity' => $this->quantity,
            'requested_quantity' => $this->requested_quantity !== null ? (float) $this->requested_quantity : (float) $this->quantity,
            'unit_snapshot' => $this->unit_snapshot,
            'unit_price' => $this->unit_price !== null ? (float) $this->unit_price : null,
            'total_paid' => (float) $this->total_paid,
            'merchant_currency_code' => $this->merchant_currency_code,
            'customer_currency_code' => $this->customer_currency_code,
            'fx_base_currency_code' => $this->fx_base_currency_code,
            'fx_rate_merchant_to_customer' => $this->fx_rate_merchant_to_customer !== null ? (float) $this->fx_rate_merchant_to_customer : null,
            'fx_market_rate_merchant_to_customer' => $this->fx_market_rate_merchant_to_customer !== null ? (float) $this->fx_market_rate_merchant_to_customer : null,
            'fx_effective_rate_merchant_to_customer' => $this->fx_effective_rate_merchant_to_customer !== null ? (float) $this->fx_effective_rate_merchant_to_customer : null,
            'fx_spread_bps' => (int) $this->fx_spread_bps,
            'fx_spread_amount' => $this->fx_spread_amount !== null ? (float) $this->fx_spread_amount : 0,
            'fx_spread_currency_code' => $this->fx_spread_currency_code,
            'money_quote_snapshot' => $this->money_quote_snapshot,
            'fx_rate_date' => $this->fx_rate_date?->toDateString(),
            'merchant_unit_price' => $this->merchant_unit_price !== null ? (float) $this->merchant_unit_price : null,
            'customer_unit_price' => $this->customer_unit_price !== null ? (float) $this->customer_unit_price : null,
            'merchant_total_amount' => $this->merchant_total_amount !== null ? (float) $this->merchant_total_amount : (float) $this->total_paid,
            'customer_total_amount' => $this->customer_total_amount !== null ? (float) $this->customer_total_amount : (float) $this->total_paid,
            'merchant_shipping_fee' => $this->merchant_shipping_fee !== null ? (float) $this->merchant_shipping_fee : null,
            'customer_shipping_fee' => $this->customer_shipping_fee !== null ? (float) $this->customer_shipping_fee : null,
            'merchant_discount_amount' => $this->merchant_discount_amount !== null ? (float) $this->merchant_discount_amount : null,
            'customer_discount_amount' => $this->customer_discount_amount !== null ? (float) $this->customer_discount_amount : null,
            'payment_status' => $this->payment_status,
            'is_inquiry' => (bool) $this->is_inquiry,
            'inquiry_status' => $this->inquiry_status,
            'agreement_snapshot' => $this->agreement_snapshot,
            'agreed_at' => $this->agreed_at?->toISOString(),
            'merchant_confirmed_at' => $this->merchant_confirmed_at?->toISOString(),
            'is_merchant_confirmed' => $this->merchant_confirmed_at !== null,
            'paid_out_at' => $this->paid_out_at?->toISOString(),
            'pickup_location_id' => $this->pickup_location_id,
            'pickup_ready_at' => $this->pickup_ready_at?->toISOString(),
            'pickup_deadline_at' => $this->pickup_deadline_at?->toISOString(),
            'pickup_grace_ends_at' => $this->pickup_grace_ends_at?->toISOString(),
            'pickup_completed_at' => $this->pickup_completed_at?->toISOString(),
            'pickup_status' => $this->pickup_status,
            'pickup_policy_snapshot' => $this->pickup_policy_snapshot,
            'pickup_extension_count' => (int) $this->pickup_extension_count,
            'pickup_no_show_marked_at' => $this->pickup_no_show_marked_at?->toISOString(),
            'pickup_no_show_reason' => $this->pickup_no_show_reason,
            'holding_fee_status' => $this->holding_fee_status,
            'holding_fee_amount' => $this->holding_fee_amount !== null ? (float) $this->holding_fee_amount : null,
            'holding_fee_payment_order_id' => $this->holding_fee_payment_order_id,
            'holding_fee_started_at' => $this->holding_fee_started_at?->toISOString(),
            'holding_fee_accepted_at' => $this->holding_fee_accepted_at?->toISOString(),
            'holding_fee_paid_at' => $this->holding_fee_paid_at?->toISOString(),
            'transaction_ref' => $this->transaction_ref,
            'source' => $this->source,
            'customer_name' => $this->customer_name,
            'customer_phone' => $this->customer_phone,
            'account_phone' => $this->account_phone,
            'payment_phone' => $this->payment_phone,
            'product' => $this->whenLoaded('product', fn() => ProductResource::make($this->product)),
            'buyer' => $this->whenLoaded('buyer'),
            'delivery' => $this->whenLoaded('delivery', fn() => [
                'delivery_status' => $this->delivery?->delivery_status,
                'status' => $this->delivery?->delivery_status,
                'delivery_type' => $this->delivery?->delivery_type,
                'type' => $this->delivery?->delivery_type,
                'physical_address' => $this->delivery?->physical_address,
                'shipping_zone' => $this->delivery?->shippingZone ? [
                    'id' => $this->delivery->shippingZone->id,
                    'zone_name' => $this->delivery->shippingZone->zone_name,
                    'destination_city' => $this->delivery->shippingZone->destination_city,
                    'destination_region' => $this->delivery->shippingZone->destination_region,
                    'flat_rate_fee' => $this->delivery->shippingZone->flat_rate_fee,
                ] : null,
                'pickup_pin' => $this->merchant_confirmed_at && $this->pickup_status === 'ready_for_pickup'
                    ? $this->delivery?->pickup_pin
                    : null,
                'buyer_release_pin' => $this->delivery?->buyer_release_pin,
                'bus_company' => $this->delivery?->bus_company,
                'waybill_tracking' => $this->delivery?->waybill_tracking_number,
                'waybill_tracking_number' => $this->delivery?->waybill_tracking_number,
                'waybill_photo_url' => $this->delivery?->waybill_photo_url,
                'events' => $this->delivery?->relationLoaded('events')
                    ? $this->delivery->events->sortBy('created_at')->map(fn ($event) => [
                        'id' => $event->id,
                        'status' => $event->status,
                        'actor_type' => $event->actor_type,
                        'actor_name' => $event->actor?->name,
                        'proof_url' => $event->proof_url,
                        'proof_mime' => $event->proof_mime,
                        'proof_type' => $event->proof_type,
                        'note' => $event->note,
                        'metadata' => $event->metadata,
                        'created_at' => $event->created_at?->toISOString(),
                    ])->values()
                    : [],
            ]),
            'dispute' => $this->whenLoaded('dispute', fn() => [
                'status' => $this->dispute?->status,
                'dispute_reason' => $this->dispute?->dispute_reason,
            ]),
            'created_at' => $this->created_at?->toISOString(),
        ];
    }
}
