[Date]
date.timezone = UTC

[PHP]
memory_limit = 512M
max_execution_time = 300
max_input_vars = 3000
upload_max_filesize = 2048M
post_max_size = 2048M

; Error reporting
log_errors = On
error_log = /var/log/php_errors.log
display_errors = Off
display_startup_errors = Off
error_reporting = E_ALL

[Session]
session.cookie_httponly = 1
session.use_only_cookies = 1
session.cookie_secure = 1

[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
opcache.revalidate_freq = 60
opcache.save_comments = 1
opcache.jit = off

[FFI]
ffi.enable = 1
ffi.preload =
